export const dummy =
  "\nWhat is the main cause of this problem? : Eating too much unhealthy food.\n\nSolution 1 : Eat more fruits and vegetables.\nDetailed Description : Eating more fruits and vegetables is a great way to get the vitamins and minerals your body needs while also reducing your calorie intake. Eating more fruits and vegetables can help you stay full longer and reduce cravings for unhealthy snacks. You can also add in some healthy proteins such as lean meats, eggs, and beans.\nServices : \n- MyFitnessPal: A free app that helps you track your food intake and exercise.\n- Healthline: A website that provides information about healthy eating and nutrition.\n\nSolution 2 : Reduce portion sizes.\nDetailed Description : Reducing portion sizes is an easy way to reduce your calorie intake without feeling deprived. You can start by reducing the size of your plate and using smaller utensils. You can also try eating slower and taking smaller bites. This will help you to feel fuller faster and reduce the amount of food you eat.\nServices : \n- Eat This Much: A meal planning service that helps you create healthy meals with the right portion sizes.\n- Nutrition.gov: A website that provides information about portion control and healthy eating.\n\nSolution 3 : Exercise regularly.\nDetailed Description : Exercise is an important part of any weight loss plan. Regular exercise can help you burn calories and build muscle, which can help you lose weight. You can start by doing simple exercises such as walking, jogging, or biking. You can also try strength training exercises such as weight lifting or bodyweight exercises.\nServices : \n- Fitbit: A fitness tracker that helps you track your activity and progress.\n- Couch to 5K: A running program that helps you gradually build up your running endurance.\n\nSolution 4 : Drink more water.\nDetailed Description : Drinking more water can help you stay hydrated and reduce cravings for unhealthy snacks. It can also help you feel fuller faster, which can help you eat less. Aim to drink at least 8 glasses of water a day. You can also add in some healthy drinks such as herbal teas or smoothies.\nServices : \n- Waterlogged: A free app that helps you track your water intake.\n- WebMD: A website that provides information about the health benefits of drinking water.";

export const greetings = [
  "I understand where you're coming from. I'm not sure if this will be super helpful, but I genuinely want to be there for you and offer any support I can.",
  "I get what you're saying. I'm not sure if I have any magic solutions, but I care about you and want to do whatever I can to help.",
  "Your problem makes sense to me. I'm not sure if I have any brilliant ideas, but I care about you and want to support you however I can.",
  "It sounds like you're going through a tough time. I'm not sure if I have all the answers, but I want you to know that I'm here for you and willing to help in any way I can.",
  "I understand the struggles you're facing. I'm not sure if I have any earth-shattering insights, but I care about you and want to be there for you.",
  "Your situation is clear to me. I'm not sure if I have any genius solutions, but I want to support you and be there for you in any way I can.",
  "I get what you're saying and I'm here for you. I'm not sure if I have all the answers, but I care about you and want to help in any way I can.",
  "Your problem makes sense to me and I want to help. I'm not sure if I have any amazing ideas, but I care about you and want to support you.",
  "It sounds like you could use some support. I'm not sure if I have any amazing solutions, but I care about you and want to be there for you in any way I can.",
  "I understand the issues you're dealing with. I'm not sure if I have any game-changing ideas, but I care about you and want to help in any way I can.",
  "I understand your predicament. I'm not sure if I have any groundbreaking solutions, but I really care about you and want to offer any help I can.",
  "Your problem makes complete sense to me. I'm not sure if I have any revolutionary ideas, but I care about you and want to be there for you in any way I can.",
  "I get what you're saying and I want to help. I'm not sure if I have any amazing insights, but I care about you and want to support you.",
  "It sounds like you could use some support. I'm not sure if I have any extraordinary solutions, but I care about you and want to be there for you in any way I can.",
  "I understand the challenges you're facing. I'm not sure if I have any life-changing ideas, but I care about you and want to help in any way I can.",
  "Your situation is clear to me and I want to be there for you. I'm not sure if I have any brilliant solutions, but I care about you and want to offer any support I can.",
  "I understand what you're going through. I'm not sure if I have any incredible ideas, but I care about you and want to help in any way I can.",
  "Your problem makes sense to me and I want to support you. I'm not sure if I have any groundbreaking insights, but I care about you and want to be there for you.",
  "It sounds like you could use some help. I'm not sure if I have any amazing ideas, but I care about you and want to be there for you in any way I can.",
  "I understand the difficulties you're experiencing. I'm not sure if I have any revolutionary solutions, but I care about you and want to offer any help I can.",
];
