import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Input } from "@chakra-ui/react";
import { useState } from "react";
import { dbService } from "../utils/fbase";
import styled from "@emotion/styled";
import { ProblemType } from "./problems";

const EXAMPLES = [
  "I want to keep up-to-date on the deep learning sector, but I don 't know where I can see it.",
  "I want to keep up-to-date on the deep learning sector, but I don 't know where I can see it.",
  "I want to keep up-to-date on the deep learning sector, but I don 't know where I can see it.",
];

const Home: NextPage = () => {
  const [problem, setProblem] = useState<string>("");

  const callApi = async () => {
    return "answer";
  };

  const changePage = () => {};

  const sendProblem = async () => {
    changePage();
    // api로 보내서 응답을 받는다.
    const response = await callApi();

    const body: ProblemType = {
      id: "",
      createdAt: new Date(),
      question: problem,
      answer: response,
    };
    await dbService.collection("problem").add(body);
    setProblem("");
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <FormContainer>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              sendProblem();
            }}>
            <Input
              value={problem}
              onChange={(e) => setProblem(e.currentTarget.value)}
            />
            <Button onClick={() => sendProblem()}>
              Send My Problem and get answer by Solomon!
            </Button>
          </form>
        </FormContainer>
        <a href="/problems">이동</a>
        <div>
          {EXAMPLES.map((item, i) => {
            return (
              <ExampleWrapper key={i} onClick={() => {}}>
                <div>See Example ➡</div>
                <div>{item}</div>
              </ExampleWrapper>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

const FormContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;

  .button {
    width: 100%;
  }
`;

const ExampleWrapper = styled.div`
  padding: 5px;
  border-radius: 8px;
  background: rgba(60, 255, 255, 0.3);
  margin: 7px;
  cursor: pointer;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: start;
`;
